[package]
name = "bl808-headers-to-svd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
pest = "2.5.2"
pest_derive = "2.5.2"
hex = "0.4.3"
svd-encoder = "0.14.2"
svd-rs = "0.14.1"
